/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPages;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author catalinacumpanasoiu1
 */
public class UsingAppPage extends javax.swing.JFrame {

    int secondsLeft = 300;
    public Timer timer;
    public TimerTask timerTask;
    
    /**
     * Creates new form UsingAppPage
     */
    public UsingAppPage() {
        initComponents();
        usingAppTimer.setText(String.valueOf(secondsLeft));
       
        System.out.println("PHASE in usingApp is: " + Constants.PHASE);
        if(Constants.PHASE == "first"){
            Constants.PHASE = "second";
        } else if(Constants.PHASE == "second"){
            Constants.PHASE = "done";
        }
        
        startTaskTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usingAppTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1900, 900));

        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Time remaining to use app:");

        usingAppTimer.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        usingAppTimer.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(usingAppTimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usingAppTimer))
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsingAppPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsingAppPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsingAppPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsingAppPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsingAppPage().setVisible(true);
            }
        });
    }
private void startTaskTimer() {
        System.out.println("Timer task started");

        timer = new Timer();
        timerTask = new TimerTask() {
            public void run() {
                secondsLeft--;
                System.out.println("Before checking timer: " + String.valueOf(secondsLeft));
                if (secondsLeft <= 0) {
                        if(Constants.PHASE == "second"){
                            RelaxPage relaxPage = new RelaxPage();
                            relaxPage.setVisible(true);
                            disposePage();
                            //this.dispose();
                        } else if(Constants.PHASE == "done"){
                            SurveyPage surveyPage = new SurveyPage();
                            surveyPage.setVisible(true);
                             disposePage();
                            //this.dispose();
                        }

                    System.out.println("Before timer cancel: " + String.valueOf(secondsLeft));
                    timer.cancel();
                    System.out.println("Timer cancelled");
 
                } else{
                    //set text for timer here
                    System.out.println("After checking timer: " + String.valueOf(secondsLeft));
                    usingAppTimer.setText(String.valueOf(secondsLeft));
                }
            }

        };
        timer.scheduleAtFixedRate(timerTask, 1000, 1000);
    }
    
    private void disposePage(){
    this.dispose();
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel usingAppTimer;
    // End of variables declaration//GEN-END:variables
}
